# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="MapConstellation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MapRegion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MapSolarSystem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("security_level", models.FloatField()),
                (
                    "constellation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="static_dump.MapConstellation",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="static_dump.MapRegion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="static_dump.MapSolarSystem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mapconstellation",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="static_dump.MapRegion"
            ),
        ),
        migrations.AddField(
            model_name="graphnode",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="static_dump.MapSolarSystem",
            ),
        ),
        migrations.AddField(
            model_name="graphedge",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edge_destinations",
                to="static_dump.GraphNode",
            ),
        ),
        migrations.AddField(
            model_name="graphedge",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edge_origins",
                to="static_dump.GraphNode",
            ),
        ),
    ]
