# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_dump', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapconstellation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mapregion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
